version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    restart: always
    privileged: true # Recommended for Jenkins to run Docker commands inside jobs
    user: root # Often used to avoid permission issues with Docker socket access
    ports:
      - "8080:8080"
      - "50000:50000"
    container_name: jenkins
    volumes:
      # Maps the local 'jenkins_home' directory to the container's Jenkins home
      - ./jenkins_home:/var/jenkins_home
      # Mounts the host's Docker socket to allow Docker-in-Docker functionality
      - /var/run/docker.sock:/var/run/docker.sock